In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os

In [2]:
os.chdir(r'C:\Users\hoang\Desktop\SIC\jupyter\vd1')

In [3]:
df = pd.read_csv('data_iris.csv', header='infer')

In [4]:
df.shape #kich thuoc bao nhieu hang bao nhieu cot

(150, 5)

In [5]:
df.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [7]:
#set aside two variables
x = df['Petal.Length']
y = df['Sepal.Length']

In [9]:
#Using the Scipy function
#Correlation and p-value
np.round(st.pearsonr(x,y),3)

array([0.872, 0.   ])

In [11]:
#using the pandas function
x.corr(y)

0.8717541573048718

In [9]:
#correlation array
np.round(df[['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']].corr(),3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Sepal.Length         1.000       -0.109         0.872        0.818
Sepal.Width         -0.109        1.000        -0.421       -0.357
Petal.Length         0.872       -0.421         1.000        0.963
Petal.Width          0.818       -0.357         0.963        1.000

In [10]:
#using the SciPy function
#Correlation and p-value
np.round(st.spearmanr(x,y),3)

array([0.881, 0.   ])

In [11]:
#Using the Scipy function
#Correlation and p-value
np.round(st.kendalltau(x,y),3) #correlation coefficient and p-value

array([0.718, 0.   ])

In [12]:
# read in another data set
df = pd.read_csv('data_studentlist.csv', header='infer')

In [13]:
df.head(3)

name gender  age  grade absence bloodtype  height  weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

In [14]:
#set aside two variables
x = df.height
y = df.weight

In [19]:
#Apply the Fisher's z-transformation.
# See the Lecture.
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)
{'low':std_error_z}

{'low': 0.2672612419124244}

In [17]:
# 95% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975))}

{'low': 0.26960396330592223, 'high': 0.992023815061445}

In [18]:
# 99% confidence interval.
# Expressed as a dictionary object.
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995))}

{'low': 0.11137578298592947, 'high': 0.9976660596052384}