In [2]:
import numpy as np

In [3]:
a = [1, 2, 3]

In [4]:
a + a

[1, 2, 3, 1, 2, 3]

In [5]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
b = np.array([1, 2, 3])

In [7]:
b*3

array([3, 6, 9])

In [8]:
b + b

array([2, 4, 6])

In [9]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [11]:
a + b

array([5, 7, 9])

In [12]:
a - b

array([-3, -3, -3])

In [13]:
a * b

array([ 4, 10, 18])

In [14]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

In [15]:
x = np.array([0, 1, 2, 3, 4, 5])

In [16]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [17]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [18]:
type(np.sqrt)

numpy.ufunc

In [20]:
type(np.exp)

numpy.ufunc

In [22]:
np.random.seed(123)
a = np.random.randint(1, 11, size = 1000)

In [23]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.median(a)

5.0

In [25]:
np.sum(a)

5485

In [26]:
np.round(np.var(a), 2)

8.19

In [27]:
np.round(np.mean(a), 2)

5.48

In [28]:
np.round(np.std(a), 2)

2.86

In [29]:
np.max(a)

10

In [30]:
np.min(a)

1

In [31]:
x = np.arange(1,11)

In [32]:
x.sum()

55

In [33]:
x.mean()

5.5

In [34]:
x.std()

2.8722813232690143

In [35]:
x.var()

8.25

In [36]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [37]:
y = np.arange(1,10)
y = y.reshape((3,-1))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
print(y.mean(axis =0))

[4. 5. 6.]


In [39]:
print(y.mean(axis =1))

[2. 5. 8.]


In [40]:
z=np.random.randint(10,size=1000)

In [41]:
z.max()

9

In [42]:
z.min()

0

In [43]:
(z > 5).sum()

392

In [44]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
sorted(set(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [47]:
a.argmax()

4

In [48]:
a.argmin()

1